# Runs the e2e tests many times to detect intermittent flakiness proactively instead of having it be
# occasionally detected in unrelated PRs.
name: e2e-flakiness-detector

on:
  schedule:
    - cron: '0 14 * * *' # daily at 1400 UTC
  workflow_dispatch:

jobs:
  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu, windows, macos]
    runs-on: ${{ matrix.runner }}-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
      - id: auth
        uses: google-github-actions/auth@v2
        # Skip auth if PR is from a fork
        with:
          workload_identity_provider: ${{ secrets.DATA_TEAM_PROVIDER_NAME }}
          service_account: ${{ secrets.DATA_TEAM_SA_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        shell: bash
        id: pnpm-cache
      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Setup Playwright browser dependencies
        run: pnpm -C vscode run test:e2e2:deps # this installs chromium etc
      - name: Run E2E tests
        run: pnpm -C vscode run test:e2e2 --project e2e --repeat-each 10
        env:
            BUILDKITE_ANALYTICS_TOKEN: ${{ secrets.BUILDKITE_ANALYTICS_TOKEN }}
            # This is required because the test collector from Buildkite is imprecise when it
            # comes to infer the branch name on GitHub action.
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
            GITHUB_REF: ${{ github.head_ref || github.ref_name }}
      - name: Upload Playwright report (failure)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright report ${{matrix.runner}}
          path: vscode/.test/e2e/reports/html
          retention-days: 30
