name: Semgrep - SAST Scan

on: [pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v3

      - name: Checkout semgrep-rules repo
        uses: actions/checkout@v3
        with:
          repository: sourcegraph/security-semgrep-rules
          token: ${{ secrets.GH_SEMGREP_SAST_TOKEN }}
          path: semgrep-rules

      - name: Run Semgrep SAST Scan
        run: |
          ls $GITHUB_WORKSPACE
          semgrep -f semgrep-rules/ $GITHUB_WORKSPACE
