name: Semgrep - SAST Scan

on: [pull_request, push]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v3

      - name: Checkout semgrep-rules repo
        uses: actions/checkout@v3
        with:
          repository: sourcegraph/security-semgrep-rules
          token: ${{ secrets.GH_SEMGREP_SAST_TOKEN }}
          path: semgrep-rules

      - name: Run Semgrep
        run: |
          semgrep --version
          ls semgrep-rules
